export enum WidgetLifecycle {
  CREATED = "CREATED",
  REGISTERED = "REGISTERED",
  MOUNTED = "MOUNTED",
  READY = "READY",
  COLLAPSED = "COLLAPSED",
  EXPANDED = "EXPANDED",
  UNMOUNTED = "UNMOUNTED",
}
