export enum QuestionBrowserMode {
  BROWSE = "BROWSE",
  SELECT = "SELECT",
  PREVIEW = "PREVIEW",
  COMPARE = "COMPARE",
  READONLY = "READONLY",
  ARCHIVE = "ARCHIVE",
  REVIEW = "REVIEW",
  MODERATION = "MODERATION",
  ORGANIZE = "ORGANIZE",
}
