export const INFRASTRUCTURE_KEYS = {
  MAINTENANCE_MODE: "MAINTENANCE_MODE",
  REGISTRATION_ENABLED: "REGISTRATION_ENABLED",
  CHALLENGE_SYSTEM_ENABLED: "CHALLENGE_SYSTEM_ENABLED",
  MODERATION_WORKFLOWS_ENABLED: "MODERATION_WORKFLOWS_ENABLED",
  ANALYTICS_SYSTEM_ENABLED: "ANALYTICS_SYSTEM_ENABLED",
  LEADERBOARD_ENABLED: "LEADERBOARD_ENABLED",
} as const;

export type InfrastructureKey = keyof typeof INFRASTRUCTURE_KEYS;
